# Generated by Django 5.0.14 on 2026-09-21 23:15

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=30, unique=True, verbose_name='Código de Lote')),
                ('peso_inicial_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Inicial Ingresado (kg)')),
                ('proveedor', models.CharField(max_length=120, verbose_name='Proveedor / Origen')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Lote de Material',
                'verbose_name_plural': 'Lotes de Materiales (Inventario)',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Máquina')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Máquina')),
                ('tipo', models.CharField(max_length=60, verbose_name='Tipo / Tecnología')),
                ('capacidad_max_kg', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8, verbose_name='Capacidad Máxima (kg)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa / Operativa')),
            ],
            options={
                'verbose_name': 'Máquina de Planta',
                'verbose_name_plural': 'Maquinarias de Fundición',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Material')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Aleación / Metal')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Técnica')),
                ('densidad_g_cm3', models.DecimalField(decimal_places=2, default=Decimal('2.70'), max_digits=5, verbose_name='Densidad (g/cm³)')),
                ('punto_fusion_c', models.IntegerField(default=660, verbose_name='Punto de Fusión (°C)')),
            ],
            options={
                'verbose_name': 'Material / Aleación',
                'verbose_name_plural': 'Materiales y Aleaciones',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código Proceso')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Proceso')),
                ('temperatura_operacion_c', models.IntegerField(blank=True, null=True, verbose_name='Temperatura Operación (°C)')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Proceso')),
            ],
            options={
                'verbose_name': 'Proceso de Fundición',
                'verbose_name_plural': 'Procesos Operativos',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EstudioPrevio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estudio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Pesaje Calibrado')),
                ('peso_calibrado_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso Verificado en Báscula Calibrada (kg)')),
                ('porcentaje_pureza', models.DecimalField(decimal_places=2, default=Decimal('99.00'), max_digits=5, verbose_name='Pureza Estimada (%)')),
                ('porcentaje_humedad', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5, verbose_name='Humedad Superficial (%)')),
                ('tolerancia_merma_max_pct', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, verbose_name='Tolerancia Máxima de Merma Admisible (%)')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador / Registrado en Báscula'), ('EN_REVISION', 'En Revisión Técnica'), ('APROBADO', 'Aprobado por Supervisión'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20, verbose_name='Estado de Aprobación')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('observaciones_metrologicas', models.TextField(blank=True, verbose_name='Observaciones Metrológicas / Calibración')),
                ('responsable_estudio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudios_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico / Operador Responsable')),
                ('supervisor_aprobador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudios_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor Aprobador')),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudio_previo', to='operaciones.lotematerial', verbose_name='Lote de Material')),
            ],
            options={
                'verbose_name': 'Estudio Previo de Contenido',
                'verbose_name_plural': 'Estudios Previos de Contenido (Gatekeeper M5)',
                'ordering': ['-fecha_estudio'],
            },
        ),
        migrations.AddField(
            model_name='lotematerial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='operaciones.material', verbose_name='Material'),
        ),
        migrations.CreateModel(
            name='RegistroMerma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_merma_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso de Merma (kg)')),
                ('tipo_merma', models.CharField(choices=[('ESCORIA', 'Escoria de Fusión / Horno'), ('VIRUTA', 'Viruta de Mecanizado / Torneado'), ('REBABA', 'Rebaba y Canales de Colada'), ('DEFECTO', 'Pieza Defectuosa / Descarte de Moldeo'), ('VOLATILIZACION', 'Pérdida por Oxidación / Volatilización')], default='ESCORIA', max_length=30, verbose_name='Tipo de Merma')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Registro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Causa del Desperdicio')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='operaciones.lotematerial', verbose_name='Lote de Material')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='operaciones.maquina', verbose_name='Máquina Utilizada')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Operador Registrador')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mermas', to='operaciones.proceso', verbose_name='Proceso Realizado')),
            ],
            options={
                'verbose_name': 'Registro de Merma Específica',
                'verbose_name_plural': 'Registros de Merma Específica (M4)',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
