# Generated by Django 5.0.14 on 2026-09-21 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('OPERADOR', 'Operador de Planta'), ('SUPERVISOR', 'Supervisor de Turno'), ('ENCARGADO', 'Encargado / Jefe de Planta')], default='OPERADOR', max_length=20, verbose_name='Rol en Planta')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('area', models.CharField(default='Fundición y Moldeo', max_length=100, verbose_name='Área Asignada')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
